# Generated by Django 2.1.3 on 2018-11-27 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IMOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob', models.CharField(max_length=30)),
                ('seal_id', models.IntegerField(unique=True)),
                ('application_name', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('environment', models.ForeignKey(default='UAT', on_delete=django.db.models.deletion.CASCADE, to='api.Environment')),
            ],
        ),
    ]
