# Generated by Django 2.1.3 on 2018-11-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_imos_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='imos',
            name='environment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Environment'),
        ),
    ]
