# Generated by Django 2.1.3 on 2018-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_imos_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='imos',
            name='status',
            field=models.CharField(choices=[('Green', 'Green'), ('Yellow', 'Yellow'), ('Red', 'Red'), ('Grey', 'Grey')], default='Green', max_length=20),
        ),
    ]
